### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/lantz_drivers#6]
I would be great to have a testsuite for our drivers. For Visa based we can use pyvisa-sim for other we might be able to do some clever mocking. The question is where should those simulated versions live. In the original Lantz there was a simulators package should we have something similar ? I know that @hgrecco was against putting the pyvisa-sim yml files here but then it means that things will be spitted over multiple repos which perhaps not very convenient.

**Comment by hgrecco** [comment]
You might be right. My main argument against putting the simulators in the same repo was mainly to let that package evolve faster and to promote pure pyvisa users (i.e. not lantz users) profit from them (and contribute!)

I see three possibilities
1. Keep the simulators repo apart and embed it using a git submodule
2. Keep the simulators repo apart and download it as part of the testing infrastructure.
3. Insert simulators in Lantz-drivers package.

I have to say that I like (2). In particular, what I am envisioning for pyvisa-sim is to have command to download zip file from github and update the definitions. Lantz can profit from this as well. Let me give a try on the weekend and I will let you know.

**Comment by alexforencich** [comment]
What about a separate package for the simulated instruments?  This would be a similar setup to how lantz is split into -core and -drivers and it would allow version control via a package manager.

**Comment by hgrecco** [comment]
@alexforencich Like a pip installable python package? 

I was thinking in something simpler. Add an API (and a command line tool) to download the zip that github generates on the fly for each repo (this can be versioned as well) and drop it in user controlled folder (for example in the already existing ~/.pyvisarc). That folder is then scanned by `pyvisa-sim` as one of the locations in which drivers might be present.

But your suggestion could definitely work as well. It would not be just folder with yml files. It would need a `setup.py` and a `__init__.py` so that pyvisa-py can hook up. But it should work. Let's continue discussing.

**Comment by alexforencich** [comment]
Well, yeah.  There is no sense in reinventing the wheel that is package management.

**Comment by MatthieuDartiailh** [comment]
A lantz-sim package would make sense.  I am +1 on this.

**Comment by MatthieuDartiailh** [comment]
I created a lantz.sim package. I will try to propose in th next weeks a basic way to get a simulated instrument in a transparent way. If any of you has ideas he is welcome to share them.
